### ISSUE TITLE
Source code for qmmonitor2?

### ISSUE THREAD

**Issue by zymurgy** [ibm-messaging/cphtestp#1]
Is there source code for qmmonitor2?  Right now it's distributed as a binary.

**Comment by stmassey** [comment]
The reason the source code for that executable is not included is that its based on the sample code amqsruaa.c which is included in the product as a sample.

**Comment by zymurgy** [comment]
Thanks,  I wasn't familiar with that particular sample app.

**Comment by hseipp** [comment]
`amqsruaa.c` does not provide the CLI options qmmonitor2 does. This makes porting to other platforms (here: s390x) unnecessary difficult. Can you please provide the patches you applied to `amqsruaa.c` to make cross-compile easier? 

P.S.: Ideally you build qmmonitor2 and cph during the docker build process, enabling multi-arch images.
