### ISSUE TITLE
Receiving MQ error 2538 in mimddle of CPH test.  Target QM appears to be running and test looks like it completed.

### ISSUE THREAD

**Issue by bransonm** [ibm-messaging/cphtestp#5]
Seeing the following error when running a test with the containerized version.  The test ran successfully using the same end point and no indication of issues on the end point.  Full log attached.

Shared library libmqic_r.so loaded ok
id=1,rate=330.20,threads=67
id=1,rate=308.70,threads=85id=1,rate=318.60,threads=94
Sending errorMsg to STDERR
Call to MQCONNX failed [Completion code: 2; Reason code: 2538]]
id=1,rate=323.30,threads=94
id=1,rate=316.10,threads=94
[ControlThread] Caught exception: Requester94: State ERROR set.
totalIterations=19000,totalSeconds=1670516108.00,avgRate=0.00
controlThread STOP
terminate called after throwing an instance of 'std::exception'
  what():  std::exception
./cphreq.sh: line 31:  3412 Aborted                 ./cph -nt $threads -ms $msgsize -rl $runlength -id 1 -tc Requester -ss 10 -iq $requestq -oq $replyq -db 1 -dx 10 -jp $port -jc $channel -jb $qmname -jt $BINDINGS -jh $host -wi 10 -to 30 $persistent_flags -ar $reconnect $extra -jl ${MQ_TLS_CIPHER} -jw ${MQ_TLS_CERTLABEL}
controlThread START

Shared library libmqic_r.so loaded okSending errorMsg to STDERR
Call to MQCONNX failed [Completion code: 2; Reason code: 2538]]
id=1,rate=0.00,threads=0
id=1,rate=0.00,threads=0
[ControlThread] Caught exception: Requester0: State ERROR set.
totalIterations=0,totalSeconds=1670516138.29,avgRate=0.00
controlThread STOP
terminate called after throwing an instance of 'std::exception'
  what():  std::exception
./cphreq.sh: line 31:  3639 Aborted                 ./cph -nt $threads -ms $msgsize -rl $runlength -id 1 -tc Requester -ss 10 -iq $requestq -oq $replyq -db 1 -dx 10 -jp $port -jc $channel -jb $qmname -jt $BINDINGS -jh $host -wi 10 -to 30 $persistent_flags -ar $reconnect $extra -jl ${MQ_TLS_CIPHER} -jw ${MQ_TLS_CERTLABEL}
Thu Dec 8 15:56:10 UTC 2022

[cphtestp-kmr4v-cphtestp.log](https://github.com/ibm-messaging/cphtestp/files/10212394/cphtestp-kmr4v-cphtestp.log)

**Comment by stmassey** [comment]
It looks like the 2538 (HOST NOT AVAILABLE) occurs at the end of the 200K test with large numbers of threads, when the peak throughput as long been achieved. It could be network/cpu congestion at the QM. Either way, increase resources available to the QM and dont attempt to run so many threads - you will have saturated your network much earlier.
