### ISSUE TITLE
Use with another base image

### ISSUE THREAD

**Issue by Stricdan26** [ibm-messaging/cphtestp#6]
The Dockerfile uses an ubuntu:18.04 image as its base image, however, in the environment we are trying to use this on, we do not have access to ubuntu. Is there a specific reason ubuntu is being used, or can the Dockerfile be converted to a ubi8 image and work fine (provided we edit the rest of the Dockerfile to work with ubi).

**Comment by stmassey** [comment]
In issue #4 - was that using Ubuntu or UBI? - Its only been tested on Ubuntu and there may be some differences on other base images. i.e. dstat and other commands may return data in different format or not support certain options. For some base images, you may need a different set of MQ client packages to install.

**Comment by stmassey** [comment]
You may also need additional packages installed onto the UBI image. The issue with the rate not being published might well be due to a missing awk package.
