### ISSUE TITLE
docker build failed

### ISSUE THREAD

**Issue by jjpan888** [ibm-messaging/cphtestp#7]
I have downloaded: 

```
9.3.0.25-IBM-MQC-UbuntuLinuxX64.tar.gz.sig
9.3.0.25-IBM-MQC-UbuntuLinuxX64.tar.gz.sha256sum
9.3.0.25-IBM-MQC-UbuntuLinuxX64.tar.gz
```

Unzipped the 9.3.0.25-IBM-MQC-UbuntuLinuxX64.tar.gz and copied the files out of MQClient to the project root directory

```
ibmmq-client_9.3.0.25_amd64.deb
ibmmq-gskit_9.3.0.25_amd64.deb
ibmmq-runtime_9.3.0.25_amd64.deb
/lap/
mqlicense.sh 
```

Changed the mq versions in Dockerfile, when running `docker build --tag cphtestp .` got below error: 

```
 => ERROR [ 6/12] RUN export DEBIAN_FRONTEND=noninteractive   && ./mqlicense.sh -accept   && dpkg -i ibmmq-runtime_9.3.0.25_amd64.deb   && dpkg -i ibmmq-gski  0.1s 
------
 > [ 6/12] RUN export DEBIAN_FRONTEND=noninteractive   && ./mqlicense.sh -accept   && dpkg -i ibmmq-runtime_9.3.0.25_amd64.deb   && dpkg -i ibmmq-gskit_9.3.0.25_amd64.deb   && dpkg -i ibmmq-client_9.3.0.25_amd64.deb   && chown -R mqperf:root /opt/mqm/*   && chown -R mqperf:root /var/mqm/*   && chmod o+w /var/mqm:
0.107 ERROR: This package is incompatible with this system.
0.107        This package was built for Linux_x86_64
0.107 
------
```

What is wrong? I am on Mac. Thanks!

**Comment by stmassey** [comment]
Hi - This container hasnt been tested on the MacOS platform. You would likely need to use the MQ Developer Toolkit for MacOS, but I dont have access to ARM hardware to try it. https://ibm.biz/mqdevmacclient

**Comment by jjpan888** [comment]
I can try on Windows if it is tested. But I thought the error indicates it was installing ibm package on Ubuntu, and the package is not compatible with Ubuntu. It is unrelated to where I am running docker build on Mac or windows. Please correct me if I am wrong. 

Another option is I could try version 9.4 on master branch instead of modifying it to 9.3. Tested on mac, same issue.

**Comment by stmassey** [comment]
Its failing because the mqlicense.sh checks whether the architecture that its running on is x86_64. Ive built it and run it under WSL2 (Ubuntu) - not that Im convinced Id want to run performance load tests from WSL2, but from a functional perspective it works.

**Comment by jjpan888** [comment]
Thanks. What alternative solution I can take? On MacOS, I don't have root privilege either to build cph from source code. JMeter is the only choice for me to test MQ servers?

**Comment by stmassey** [comment]
I dont know your requirements. If you just want to check that the servers are up and responding to messages, then running in WSL2 would be fine. If I were attempting to understand the maximum performance of the deployed environment, then running from a laptop (WSL2) potentially over Wifi, would not be the ideal topology.
